### ISSUE TITLE
node_modules are required

### ISSUE THREAD

**Issue by Striffly** [Foundry376/Mailspring-Plugin-Starter#1]
**Problem** 
`node_modules` are required for plugin execution

**Solution** 
- Remove `node_modules` from .gitignore
- Build typescript with webpack

**Comment by graphcareful** [comment]
Hello I am trying to build a plugin and i'm not a node expert. Is this demo not built with typescript for some technical reason? When I try to create a .tsx file tsc complains about not being able to find the module 'mailspring-exports'
