### ISSUE TITLE
[Request] Grammarly Plugin

### ISSUE THREAD

**Issue by jackafoley** [Foundry376/Mailspring-Plugin-Starter#4]
I must say Grammarly has become an essential part of my life. I love mailspring, but it has no integration with Grammarly.  I will pay someone to create a Grammarly integration for myself and others to use. Thank you!

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Please create a new Feature Suggestion on our Discourse instead: https://community.getmailspring.com/c/features/12
