### ISSUE TITLE
contact for billing support at Mailspring

### ISSUE THREAD

**Issue by stevejamm1** [Foundry376/Mailspring-Plugin-Starter#5]
I have sent a few emails to hello@getmailspring.com regarding my pro billing - it has been read but no one replies? How can I get a hold of a billing support person at Mailspring?

**Comment by Phylu** [comment]
@stevejamm1 Sorry for the inconvenience. I have forwarded your request. I will close this issue though, as you won't be able to get any billing advice in the Plugin Starter Repository. ;-)

**Comment by bengotow** [comment]
Hey @stevejamm1! I'll reach out and we'll get this sorted, sorry for the hassle!

Edit: If you could email me directly at ben@foundry376.com, I'd appreciate it! It looks like there aren't any commits in your account for me to look up an email address with :-)

**Comment by stevejamm1** [comment]
It was sorted already. I raised this ticket before you contacted me because I was not sure how to raise a support request, or because I had not received a reply so I sought out a different method.

All good. Just delete the support request.
best
steve
