### ISSUE TITLE
billing

### ISSUE THREAD

**Issue by Babykimberly** [Foundry376/Mailspring-Plugin-Starter#6]
I have been billed every month 7.99 twice on my discover and then 7,99 on my visa,  for several months because I had to open new accounts because I couldn't get on and I email tech and no response.  My 2 email are dawnpenuel@aol.com and dawnpenuel59@gmail.com.  I would like to get a credit for the months that I have been paying and triple for one account because the service didn't work and I tried tech support and no response and I could see they never pick up the msg.  

Please get back with me 

Dawn Penuel

**Comment by bengotow** [comment]
Hey Dawn! Thanks for reaching out - I was able to find your duplicate accounts and it looks like you do have three copies of one of your Mailspring IDs that are all on a monthly subscription. I'll refund the duplicate charges as far back as Stripe will let me - thank you for supporting the product! You should receive refund emails from Stripe in a few minutes.

If you have any more billing related issues, feel free to message me at ben@foundry376.com,
